//! Machine-readable contract consumed by later tool handlers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SafetyClass {
    Read,
    Write,
    Destructive,
}
#[derive(Debug, Clone, Copy)]
pub struct RouteSpec {
    pub group: &'static str,
    pub action: &'static str,
    pub method: &'static str,
    pub path: &'static str,
    pub required_args: &'static [&'static str],
    pub projection: &'static str,
    pub safety: SafetyClass,
    pub compatibility: &'static str,
}
pub const ROUTE_MATRIX: &[RouteSpec] = &[
    RouteSpec {
        group: "servers",
        action: "list",
        method: "GET",
        path: "/servers?page&per_page",
        required_args: &[],
        projection: "ServerSummary[]",
        safety: SafetyClass::Read,
        compatibility: "none",
    },
    RouteSpec {
        group: "servers",
        action: "validate",
        method: "POST",
        path: "/servers/{uuid}/validate",
        required_args: &["uuid"],
        projection: "Json",
        safety: SafetyClass::Write,
        compatibility: "POST->GET on 405/routing 404",
    },
    RouteSpec {
        group: "projects",
        action: "crud",
        method: "GET|POST|PATCH|DELETE",
        path: "/projects[/{uuid}]",
        required_args: &[],
        projection: "ProjectSummary",
        safety: SafetyClass::Destructive,
        compatibility: "none",
    },
    RouteSpec {
        group: "projects",
        action: "environments",
        method: "GET|POST|DELETE",
        path: "/projects/{project_uuid}/environments[/{name}]",
        required_args: &["project_uuid"],
        projection: "Json",
        safety: SafetyClass::Destructive,
        compatibility: "none",
    },
    RouteSpec {
        group: "applications",
        action: "summary",
        method: "GET",
        path: "/applications[?tag]",
        required_args: &[],
        projection: "ApplicationSummary[]",
        safety: SafetyClass::Read,
        compatibility: "none",
    },
    RouteSpec {
        group: "applications",
        action: "crud",
        method: "GET|PATCH|DELETE|POST",
        path: "/applications/{uuid}|/applications/{kind}",
        required_args: &["uuid or kind"],
        projection: "ApplicationSummary/ActionResult",
        safety: SafetyClass::Destructive,
        compatibility: "none",
    },
    RouteSpec {
        group: "applications",
        action: "env_lifecycle",
        method: "GET|POST|PATCH|DELETE",
        path: "/applications/{uuid}/envs[/{env_uuid}]",
        required_args: &["uuid"],
        projection: "EnvironmentVariable[]",
        safety: SafetyClass::Destructive,
        compatibility: "none",
    },
    RouteSpec {
        group: "applications",
        action: "operations",
        method: "POST|DELETE",
        path: "/applications/{uuid}/{start|stop|restart|move|migrate|rollback}|/applications/{uuid}/previews/{pull_request_id}",
        required_args: &["uuid"],
        projection: "ActionResult",
        safety: SafetyClass::Destructive,
        compatibility: "none",
    },
    RouteSpec {
        group: "applications",
        action: "logs_storage_tags",
        method: "GET|POST|PATCH|DELETE",
        path: "/applications/{uuid}/logs|/applications/{uuid}/storages[/{storage_uuid}]|/applications/{uuid}/tags[/{tag_uuid}]",
        required_args: &["uuid"],
        projection: "BoundedLogs/Json",
        safety: SafetyClass::Destructive,
        compatibility: "none",
    },
    RouteSpec {
        group: "databases",
        action: "all",
        method: "GET|POST|PATCH|DELETE",
        path: "/databases[/{uuid}|/{type}] and /databases/{uuid}/{envs|backups|storages|tags}",
        required_args: &[],
        projection: "DatabaseSummary/BoundedLogs/Json",
        safety: SafetyClass::Destructive,
        compatibility: "none",
    },
    RouteSpec {
        group: "services",
        action: "all",
        method: "GET|POST|PATCH|DELETE",
        path: "/services[/{uuid}] and /services/{uuid}/{applications|databases|storages|tags}",
        required_args: &[],
        projection: "ServiceSummary/Json",
        safety: SafetyClass::Destructive,
        compatibility: "none",
    },
    RouteSpec {
        group: "deployments",
        action: "list_get_trigger_cancel_logs",
        method: "GET|POST",
        path: "/deployments[/{uuid}]|/deployments/applications/{uuid}|/deploy|/deployments/{uuid}/cancel",
        required_args: &[],
        projection: "DeploymentSummary/DeploymentProjection/BoundedLogs",
        safety: SafetyClass::Destructive,
        compatibility: "none",
    },
    RouteSpec {
        group: "configuration",
        action: "system_s3_tags",
        method: "GET|POST|PATCH|DELETE",
        path: "/system|/s3[/{uuid}]|/tags[/{uuid}]|/scheduled-tasks[/{uuid}]",
        required_args: &[],
        projection: "BoundedJson",
        safety: SafetyClass::Destructive,
        compatibility: "none",
    },
    RouteSpec {
        group: "diagnostics",
        action: "diagnose",
        method: "GET",
        path: "/applications/{uuid}/diagnose|/servers/{uuid}/diagnose",
        required_args: &["uuid"],
        projection: "BoundedDiagnostic",
        safety: SafetyClass::Read,
        compatibility: "none",
    },
];
pub fn routes_for(group: &str) -> impl Iterator<Item = &'static RouteSpec> {
    ROUTE_MATRIX
        .iter()
        .filter(move |route| route.group == group)
}
